### ISSUE TITLE
Bug Fix Release v3.30.23.1 checklist

### ISSUE THREAD

**Issue by e-perl-NOAA** [nmfs-ost/ss3-source-code#648]
# Release checklist

## General checklist before pre-release and release
- [x] SS3 testing and debugging completed (RM/IT)
- [x] Check artifact from the `call-build-ss3-warnings` GitHub action for useful warnings (RM/IT/EP)
- [x] r4ss updated (IT/EP)

## Checklist for before release
- [x] Run the ss3-doc [bug fix release workflow](https://github.com/nmfs-ost/ss3-doc/actions/workflows/release_bug_fix.yml) (EP). 
- [x] Code committed and tagged in repo as `v3.30.23.1`, which will trigger a GHA to build the release executables (EP) (Instructions on [how to push a a local tag to a remote](https://github.com/nmfs-ost/ss3-source-code/wiki/Stock-Synthesis:-practices-for-maintainers#how-to-push-a-local-tag-up-to-github))
- [x] Exe and .tpl archived on [Google drive](https://drive.google.com/drive/folders/1Gh_dXi8v3rqawpwn2N6yaaEXZPq6G2io) (EP)
- [x] All exes added to GitHub releases as `v3.30.23.1` (EP) (get exes in the artifacts of the GHA that built the release exes)
- [x] Send out release announcement message to the [SS3 forum](https://groups.google.com/g/ss3-forum) (RM)
- [x] Add to release discussion on GitHub repository (EP)

## Checklist for after release
- [x] Update user-example models using [this github action](https://github.com/nmfs-ost/ss3-user-examples/blob/main/R/update_examples.R) and tag with new release number after updating (EP)
- [x] Update test models using [this github action](https://github.com/nmfs-ost/ss3-test-models/actions/workflows/update-ss3-models.yml) and tag with new release number after updating (EP)
- [x] Update executables in the [SAC tool](https://github.com/shcaba/SS-DL-tool) (also suggest updating the input files to the .ss_new files (EP/JC)

**Comment by shcaba** [comment]
Added to SAC tool
